### ISSUE TITLE
Loops not working properly

### ISSUE THREAD

**Issue by rdebath** [yakubin/lunafuck#1]
The loops should be `while do ... done` not `repeat ... until`

This is a hello world.

    >++++++++[-<+++++++++>]<.>[][<-]>+>-[+]++>++>+++[>[->+++<<+++>]<<]>-----.
    >->+++..+++.>-.<<+[>[+>+]>>]<--------------.>>.+++.------.--------.>+.>+.

and [here is a mandelbrot set](https://github.com/rdebath/Brainfuck/blob/master/testing/Mandelbrot.b).

**Comment by yakubin** [comment]
Loops are fixed. Mandelbrot.b still doesn't work though, so I think it's caused by a different bug.
Thanks for the bug report anyway.

**Comment by rdebath** [comment]
I think your remaining bug is only that you're using 8-bit branches rather than 32bit.

**Comment by yakubin** [comment]
You're right.
I've fixed it in 03044af.
Now a lot more Brainfuck programs work (in fact now every Brainfuck program I compile with lunafuck works), so thanks for the help with tracking down the problem!
